name: .NET Core

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ./BulkyBook
      run: dotnet restore
    - name: Build all projects
      working-directory: ./BulkyBook
      run: dotnet build --configuration Release --no-restore
